branches:
  only:
    - master
    - development
    - gh-27
language: ruby
bundler_args: --without development integration
script: "bundle exec gem list && bundle exec rake spec"
rvm:
- 1.9.3
- 2.0.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.2"
    - PUPPET_GEM_VERSION="~> 3.8"
    - PUPPET_GEM_VERSION="~> 3.7"

matrix:
  exclude:

notifications:
  email: corey@logicminds.biz
