branches:
  only:
    - master
    - development
language: ruby
bundler_args: --without development
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7"
    - PUPPET_GEM_VERSION="~> 3.2"
    - PUPPET_GEM_VERSION="~> 3.6"
    - PUPPET_GEM_VERSION="~> 3.7"

matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.2"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.6"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.7"

notifications:
  email: corey@logicminds.biz
